---
- hosts: database
  sudo: yes
  vars:

  tasks:

  - name: Postgresql | Ensure postgresql is listening from everywhere
    lineinfile: dest="{{ postgresql_etc_directory }}/postgresql.conf" regexp="^listen_addresses =" line="listen_addresses ='*'" state=present

  - name: Postgresql | Ensure any postgresql user can connect using its password
    lineinfile: dest="{{ postgresql_etc_directory }}/pg_hba.conf" regexp="^host all all all md5" line="host all all all md5" state=present
    notify:
    - Postgresql | Ensure service is reloaded

  - name: Postgresql | Ensure admin user exists for postgresql
    postgresql_user: name={{ postgresql_myadmin_user }} password={{ postgresql_myadmin_password }} role_attr_flags=SUPERUSER
    sudo_user: "{{postgresql_admin_user}}"

  roles:

  handlers:
    - name: Postgresql | Ensure service is reloaded
      service: name=postgresql state=reloaded
      notify:
      - Postgresql | Ensure service is restarted

    - name: Postgresql | Ensure service is restarted
      service: name=postgresql state=restarted
