---
- name: ensure package necessary
  package:
    name: "{{item}}"
  with_items:
    - ca-certificates
  tags:
    - docker

- name: reference the apt key for docker server
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  tags:
    - docker

- name: ensure the repository is present
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    state: present
  tags:
    - docker

- name: ensure docker is up to date
  package:
    name: docker-engine
    state: present
  tags:
    - docker

- name: ensure docker-compose is up to date
  package:
    name: docker-compose
    state: present
  tags:
    - docker

- name: ensure ubuntu user is in docker group
  user:
    name: vagrant
    groups: docker
    append: yes


- name: Create a network
  docker_network:
    name: docker